### ISSUE TITLE
Make the Website Responsive

### ISSUE THREAD

**Issue by YashBANSAL392** [YashBANSAL392/HacktoberFest2023#1]

**Comment by kartikhustles** [comment]
I wanna work on this issue, pls assign it to me

**Comment by ayusharma-20** [comment]
Hi Yash,

I hope this message finds you well. I came across issue. After reviewing it, I'm keen on taking this up and working towards a solution. I believe I can make a meaningful contribution to this task. Would it be possible to have this issue assigned to me?

I truly appreciate your time and consideration.

Looking forward to your response.
