### ISSUE TITLE
Make Changes in CSS code and resolve the issue in Project Section

### ISSUE THREAD

**Issue by YashBANSAL392** [YashBANSAL392/HacktoberFest2023#3]

**Comment by bhalerao-2002** [comment]
Hi @YashBANSAL392 ,
Please assign me.

**Comment by ayusharma-20** [comment]
Hi Yash,

I hope you're doing well. I came across this issue related to the CSS code in project section. Given my experience in frontend development, I believe I can contribute effectively to this.

Could you please consider assigning this issue to me? I'm excited to work on it.

Thank you for your time and consideration.

**Comment by rajiv57** [comment]
Hello @YashBANSAL392 i want to work on this issue, please assign this to me.

**Comment by kartikhustles** [comment]
Hello Bhaiya, I want to work on this Issue

Thank You in advance.

**Comment by kartikhustles** [comment]
kindly check it
