### ISSUE TITLE
Check the lower most section and change the CSS of that

### ISSUE THREAD

**Issue by YashBANSAL392** [YashBANSAL392/HacktoberFest2023#5]

**Comment by seabeePraveen** [comment]
hello @YashBANSAL392 i want to work on this issue please assign this to me
Thank you!

**Comment by ayusharma-20** [comment]
Hi Yash,

I hope you're doing well. 
I believe that I have a good hand in frontend development and I'm really excited to solve this issue. Please consider me for the same . Thank you..

**Comment by rajiv57** [comment]
Hello @YashBANSAL392 i want to work on this issue, please assign this to me

**Comment by kartikhustles** [comment]
Hello Bhaiya, I want to work on this Issue

Thank You in advance.
